
using Vonage.Extensions;

namespace VonageNumberInsights
{
    public class Program
    {
        public static void Main(string[] args)
        {
            //Most of this is boilerplate code generated by the ASP.NET Core Web API template
            var builder = WebApplication.CreateBuilder(args);

            builder.Services.AddControllers();
            builder.Services.AddEndpointsApiExplorer();
            builder.Services.AddSwaggerGen();

            //This is where we register the Vonage client to the DI container so that it's available to our Controller
            builder.Services.AddVonageClientScoped(builder.Configuration);

            var app = builder.Build();

            if (app.Environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI();
            }

            app.UseHttpsRedirection();

            app.UseAuthorization();


            app.MapControllers();

            app.Run();
        }
    }
}
